### ISSUE TITLE
Add /.autorelabel when changing from lower to higher SELinux state?

### ISSUE THREAD

**Issue by bschonec** [blackstar257/ansible-selinux#4]
Would it make sense to add the /.autorelabel file to have the selinux labels fixed on the next reboot?

Changing from disabled to either permissive or enforcing might cause issues if a filesystem relabel isn't performed.

**Comment by blackstar257** [comment]
Any ideas on how to ensure Idempotence with this?

**Comment by blackstar257** [comment]
Maybe based on if for the selinux module task changes and if selinux_state is set for anything over than disabled.... hmm
